title: Y. Sakishita
lang: ja
url: https://y-saki26.github.io
tagline: Website of Y. Sakishita
description: Website summarizing Yuki Sakishita's achievements
author:
  name: Yuki Sakishita
  url: https://y-saki26.github.io
twitter:
  username: UndercapeY
  card: summary
logo: /assets/img/jdenticon_Y.__Sakishita.jpg
google_site_verification: Ox5gxPoyK55bmXwER1X9Y3rVrA9StwWIaERDPJRkfJg
google_analytics: G-65XGBRY6HB
show_downloads: false
github:
  is_project_page: true
  is_user_page: true
theme: jekyll-theme-minimal
plugins:
  - jekyll-sitemap
